export const commonLanguages = [
    "English",
    "Mandarin",
    "Spanish",
    "Arabic",
    "French",
    "Italian",
    "German",
    "Portuguese",
    "Japanese",
    "Korean",
    "Vietnamese",
    "Cantonese",
    "Greek",
    "Hindi",
    "Punjabi",
    "Filipino",
    "Tamil",
    "Indonesian",
    "Nepali",
    "Sinhalese",
] as const;